### ISSUE TITLE
截图怎么办？ :smirk:

### ISSUE THREAD

**Issue by 985892345** [ColdRain-Moro/auto-study-league-lesson#1]
那个请求之前抓到过，但感觉你真正看没有不是取决于它，里面还有加密的一些请求

**Comment by hiyasame** [comment]
🤔🤔我也感觉 下期青年大学习出来了再研究一下

**Comment by hiyasame** [comment]
截图的话可以尝试渲染完成跳转的网页🤔

**Comment by 985892345** [comment]
我们截图是要求的发朋友圈

**Comment by hiyasame** [comment]
😂我从来没交过截图 我们班委直接查后台

**Comment by 985892345** [comment]
啊，还可以查后台，那目前你用的这个接口能成功不？

**Comment by hiyasame** [comment]
还没试过 至少进去过后表面上是已学习 但不知道有没有记到后台上

**Comment by 985892345** [comment]
这个之前我试过，但在不同的平台上会显示不同，比如：我在手机上打开后关闭显示已学习，但再去电脑上看，发现我是未学习状态。所以之前试了这接口感觉没有用

**Comment by ColdRain-Moro** [comment]
这里找到一个查是否学习的接口
![image](https://user-images.githubusercontent.com/69996135/173189134-0c52085c-f823-49fe-9f09-cceb6bcf2cba.png)
![image](https://user-images.githubusercontent.com/69996135/173189228-d6deb26c-2cff-488e-b5ab-d66b7a70b6a4.png)
https://be-prod.redrock.cqupt.edu.cn/big-study-statistcs/front/select

**Comment by hiyasame** [comment]
![image](https://user-images.githubusercontent.com/69996135/173189296-fce915d4-e764-41ed-b249-1f6cba73bae2.png)
这里找到一个可以查是否学习的接口

**Comment by 985892345** [comment]
😏好东西

**Comment by 985892345** [comment]
要什么参数不？

**Comment by hiyasame** [comment]
没弄清楚 我也在琢磨😢
