### ISSUE TITLE
[BUG]已测试，打不上

### ISSUE THREAD

**Issue by newmilkiceonwall** [ColdRain-Moro/auto-study-league-lesson#2]
这周新号测试了，打不上。

**Comment by hiyasame** [comment]
我这边没问题 小程序首页的显示有问题 有时候打了也会显示没打
要看是否打上的话可以在 我的-已学课程 里看

**Comment by newmilkiceonwall** [comment]
在#1 里面提到电脑显示未学习，手机显示已学习。我这里测试的情况是，在公众号大学习的首页依旧显示“未学习”，但是在“我的”——“已学课程”中有学习记录。首页点击最新一期显示“未学习”的内容，会提示“已经学习，是否重学”（大意如此记不清原文），点击取消后，退出，再进入，显示已经学习。
